### ISSUE TITLE
Add user guide states on swap

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/swayswap#132]
Today our button on the Swap page just shows text for loading, swap, and insufficient liquidity we should improve to show;

- [x] Select token
- [x] Enter amount
- [x] Insufficient {{token}} balance
- [x] Insufficient liquidity
- [x] Swap
- [x] (Spiner when loading)

**Comment by LuizAsFight** [comment]
@pedronauck FYI pool page has similar behavior
