### ISSUE TITLE
Add swap informations

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#144]
When swapping we should show some information;

* [ ] Exchange rate: `1 ETH ~= 2000 DAI` this information should be calculated on the front-end
* [ ] Price impact: `~20%` this value should be returned from the contract
* [ ] Liquidity provider fee: `~0.3%` this value should be returned from the contract

**Comment by kallemoen** [comment]
Designs can be found here: https://miro.com/app/board/uXjVOynDXW4=/

@luizstacio Waiting on feedback
