### ISSUE TITLE
Add pool creation preview

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#146]
When creating a pool we should show some information about the poll status and what is the expected results;

* Slippage: tokens to be used between:
   * Depositing: `0.8 ~ 1ETH` : calculates on the front end
   * Depositing: `1800 ~ 2000DAI`: calculates on the front end
      where the second value is the value inputted by the user and the first one is the tolerance;
  * Estimated LP Tokens: `0.8 ~ 2 LP`: this value could be returned by the contract

**Comment by luizstacio** [comment]
ping: @kallemoen

**Comment by kallemoen** [comment]
Designs can be found here: https://miro.com/app/board/uXjVOynDXW4=/

@luizstacio Waiting on feedback
