### ISSUE TITLE
Validate pool creation values

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#148]
When creating a pool with existing liquidity the user needs to provide an exact ratio of the current on reserves;

We can validate on the front-end by using the pool info;
```
(eth_reserve / token_reserve) === (eth_inputed by the user / token_inputed by the user)
```
**Note**; This should also consider slippage when its implemented: https://github.com/FuelLabs/swayswap/issues/147

**Comment by LuizAsFight** [comment]
@luizstacio 
ratios are gonna be hard to match exactly equal in the formula you proposed, so I'm guessing we need an initial slippage (even if screen is not showing yet). For example:

Let's assume ratio is `0.002` or `1 ETH -> 500 DAI`.

If the user wants to add liquidity with `2.12 ETH`, he would need to put exactly `1060 DAI` for it to work.

I'll use 0.5% of slippage as default for now, ok?
so in this logic, accepted ratio will be `0.0015` to `0.0025`. Is that right?

**Comment by luizstacio** [comment]
> @luizstacio ratios are gonna be hard to match exactly equal in the formula you proposed, so I'm guessing we need an initial slippage (even if screen is not showing yet). For example:
> 
> Let's assume ratio is `0.002` or `1 ETH -> 500 DAI`.
> 
> If the user wants to add liquidity with `2.12 ETH`, he would need to put exactly `1060 DAI` for it to work.
> 
> I'll use 0.5% of slippage as default for now, ok? so in this logic, if pool ratio is `0.002`, with `0.5%` of slippage tolerance, accepted ratio will be from `0.0015` to `0.0025`.
> 
> Is that right?

Sure 0.5% works fine
