### ISSUE TITLE
Add block-explorer link to transactions

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#173]
- [ ] Add the transaction hash with a link (https://fuellabs.github.io/block-explorer-v2/transaction/$HASH) to the transaction's page on the block explorer
- [ ] When clicking the wallet address, go to the address's block explorer page to view all its transactions
- [ ] Make sure the block explorer works with the current devnet URL, etc.

**Comment by pedronauck** [comment]
Closed in favor of #307
