### ISSUE TITLE
Can't open wallet after swap

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/swayswap#250]
**To recreate:**
- New private window
- Visit https://fuellabs.github.io/swayswap
- Faucet .5 eth
- Swap max eth -> dai
- Attempt to click on wallet "button greyed out, wont open"

Note, if I refresh the page, then I can click on the wallet just fine.

**Comment by pedronauck** [comment]
I think this is fixed in the [new versions](https://swayswap-5j9esl3bn-fuel-labs.vercel.app/), just need to deploy @luizstacio
