### ISSUE TITLE
Odd wallet remainder after ETH Swap to Dai

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/swayswap#252]
1. New private browser window
2. Visit https://fuellabs.github.io/swayswap/swap
3. Faucet Eth
4. Click "Max" for Eth
5. Swap for Dai
6. The remaining ETH balance in the wallet should be zero, but is instead: 0.000000001 ETH

I think there might be either a fee, calculation or display issue here.

**Comment by pedronauck** [comment]
fixed, will be released soon
