### ISSUE TITLE
Add block-explorer links on transactions

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#307]
1. Add the transaction hash with a link to the transaction's page on the block explorer
2. When clicking the wallet address, go to the address's block explorer page to view all its transactions
3. Make sure the block explorer works with the current `devnet` URL, etc.

**Comment by adlerjohn** [comment]
> When clicking the wallet address, go to the address's block explorer page to view all its transactions

This should happen when you click the wallet address _in the wallet popup_ (as opposed to replacing the current functionality of opening the popup when clicking the address).
