### ISSUE TITLE
Fix layout flicker on swap

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#353]
When data is loading on the inputs or on the swap preview the layout should not resize.

Note:
1. When the input doesn't have an amount it didn't show it below, we could leave the space empty
2. When the max is not allowed yet but is loading it could show a placholder.
3. When inverting it has a delay between changing the values when not having a balance after it has balance on both coins only the max button is delayed.
https://user-images.githubusercontent.com/3941923/176050346-e6ac73e9-0865-411d-b198-cf0ad72023c8.mov

**Comment by LuizAsFight** [comment]
this may involve some different issues:

- [ ]  #355

**Comment by LuizAsFight** [comment]
@luizstacio are we on a good shape to close this issue now?
