### ISSUE TITLE
Submit swapsway error

### ISSUE THREAD

**Issue by tuantiensiu** [FuelLabs/swayswap#402]
This is have error when I submit request Give me ETH
![enter image description here](https://i.imgur.com/FjhQIEf.png)

**Comment by Falpatorr** [comment]
I have the same issue

**Comment by MziyandaAstro** [comment]
I have a similar error too. After launching the app, I'm prompted to request for testnet ETH which fails (it doesn't even ask for address).

**Comment by Cryptokhad** [comment]
I am recieving this : Invalid faucet response: {"error":"captcha failed"} after requesting faucet funds

**Comment by luizstacio** [comment]
We are looking into it
