### ISSUE TITLE
Create a contribute guide

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/swayswap#54]

**Comment by pixelsbyeryc** [comment]
Would love to see some guidelines on: 
- How to use conventional commits in Fuel repositories. 
- How to name PRs
- Whether to fork or clone the repo directly

These are all things Luiz chatted with me about... Specifically about how they affect the `CHANGELOG`s.

It may be seamless for people who are used to using git in teams, but they weren't concepts I was aware of (after nearly 7 years of git using it only for myself and small website development teams who knew just a little more than me).

**Comment by pixelsbyeryc** [comment]
Proposal for the Guidelines:

## General
- Contributions must follow the [GitHub Flow](https://guides.github.com/introduction/flow) with slight modifications. Create a new branch and pull request it to develop. Never directly to master.
- All classes, functions and variables names must be in english. Avoid abbreviations.

## Commits
- Use [conventional commits](conventionalcommits.org).
- Make it descriptive: describe what the commit is doing in an objective and succinct approach. If needed, use multiple lines.
- Use the present tense ("Add feature" not "Added feature") and the imperative mood ("Move class to..." not "Moves class to...") on commits and pull requests. [See @gabrielkoerich's guidelines](https://github.com/gabrielkoerich/guidelines)
- No emojis 😢: it pollutes the `CHANGELOG`.

## [Language-specific Coding Style]
See @gabrielkoerich's [guidelines repo](https://github.com/gabrielkoerich/guidelines).

It might be worth having a set of rules for that, like: using tabs or spaces? 2 or 4 spaces? etc

**Comment by eureka-cpu** [comment]
My contributing doc may not include everything listed here, feel free to make suggestions where they make sense!
