### ISSUE TITLE
SwaySwap needs a readme & about section

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/swayswap#59]

**Comment by pixelsbyeryc** [comment]
@eureka-cpu I can help out with that 😄 

Are you looking for something like [Uniswap Interface](https://github.com/Uniswap/interface)?

Or something more complete, with a structure like:
1. Header
    1. Title
    2. Short Description
    3. Badges
    4. Image of the UI
2. About the Project
3. How to Install
4. Contributing
5. License

**Comment by pixelsbyeryc** [comment]
Tracking in PR: #60

**Comment by eureka-cpu** [comment]
First off, thanks so much!

I think something like: 

>     1. Header
>        
>        1. Title
>        2. Short Description
>        3. Badges
>        4. Image of the UI
> 
>     2. About the Project
> 
>     3. Contributing
> 
>     4. License

would be great, since it is close to being completed it would be nice for its appearance to newcomers to also be complete looking (:

**Comment by yogeshcenation** [comment]
See this and my profile for a inspirational profile readme 
https://github.com/yogeshcenation/yogeshcenation/blob/cf0ae44450f97589b323f4308d6d589d25f470ff/README.md

**Comment by pixelsbyeryc** [comment]
Tracking here:
- #59

cc @yogeshcenation
