### ISSUE TITLE
[Styles] Set up default Tailwind color scales for the platform using Radix UI Colors

### ISSUE THREAD

**Issue by pixelsbyeryc** [FuelLabs/swayswap#69]
_Originally posted by @pixelsbyeryc in https://github.com/FuelLabs/swayswap/pull/53#issuecomment-1113731370_

**Comment by pixelsbyeryc** [comment]
Coming up, by @pedronauck: https://github.com/pedronauck/fuel-design-system

**Comment by pedronauck** [comment]
Yeap, the repo now is here @pixelsbyeryc https://github.com/fuellabs/fuel-design-system
