### ISSUE TITLE
[Styles] Revamp the swap design

### ISSUE THREAD

**Issue by pixelsbyeryc** [FuelLabs/swayswap#70]
**I can take the lead on this, since it might not be a priority for the team.**

I'm testing a revamp to the design using [Radix UI Colors](https://www.radix-ui.com/docs/colors/palette-composition/the-scales).

**Here's the [Figma File I'm working with](https://www.figma.com/file/0oWykF2bYKj9hJ1XuDPaAP/SwaySwap?node-id=0%3A1).**

**Colors:**
- Accent colors: [`mintDark`](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#mint)
- Neutral colors: [`slateDark`](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#slate)

**Font:** Inter (with a few caveats)

**Icons:** [Heroicons](https://heroicons.com/) - a library from the guys that created TailwindCSS.

Let me know what you think, how it's looking. I'll introduce some of the changes in future commits. Don't want to proceed with the PR until we have some of these things "approved". @luizstacio in this case, should I open a new issue and move the PR to a draft? What's the best practice?

### Entire UI (WIP)
<img width="1432" alt="Screen Shot 2022-04-29 at 3 10 24 AM" src="https://user-images.githubusercontent.com/101464991/165892925-0614f95e-4746-4dec-907f-c043bd5505ae.png">

### Menu Item States
<img width="915" alt="Screen Shot 2022-04-29 at 3 14 37 AM" src="https://user-images.githubusercontent.com/101464991/165893325-f769cf7b-d900-4eaf-89fc-8aac2407410d.png">
 
### Menu Wallet Design (WIP)
<img width="563" alt="Screen Shot 2022-04-29 at 3 14 57 AM" src="https://user-images.githubusercontent.com/101464991/165893371-78c2bb88-159d-4adf-9fe4-fb2f72f5f0bd.png">

_Originally posted by @pixelsbyeryc in https://github.com/FuelLabs/swayswap/issues/53#issuecomment-1112911082_

**Comment by pixelsbyeryc** [comment]
Coming up, by @pedronauck: https://github.com/pedronauck/fuel-design-system

**Comment by luizstacio** [comment]
We have made a lot of improvements on the UI, thanks for your contributions, please take a look and open new issues if you find something you can help with.

Thanks for the contribution,
