### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/swayswap#94]
The app should have a landing page with a brief description of what it is, why it's important and a button to get started. 

Take Uniswap landing as an example.

**Comment by kallemoen** [comment]
Design:
![MacBook Pro 14_ - 6](https://user-images.githubusercontent.com/13684960/172043303-9e2893df-3b02-439d-b075-dc45beb1cb0f.png)

This is the background asset needed:
![Uploading bg-swayswap.png…]()

**Comment by SilentCicero** [comment]
Oh one thing @kallemoen could we have a larger launch app button below the text. So everything gets moved up a bit and there is a left aligned green button "Launch App" in addition to the one in the top right hand corner.

**Comment by kallemoen** [comment]
Here's a bigger version: 
https://www.dropbox.com/s/68glcpzw3auaccv/MacBook%20Pro%2014_%20-%207.png?dl=0

**Comment by SilentCicero** [comment]
```
SwaySwap is the first ever DEX build on a modular execution layer: Fuel.

Built with an entirely new language (Sway), virtual machine (FuelVM), and UTXO based blockchain (Fuel), you can now experience a demonstration of the next-generation of scaling beyond layer-2’s and monolithic design.

[ Launch app ]
```

@kallemoen
