### ISSUE TITLE
Auto-faucet upon landing with zero balance

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/swayswap#95]
If a user doesn't have a balance, SwaySwap should auto facuet me coin and present a message nicely saying "Fauceting you test Ether".

I shouldn't need to manually hit the faucet button.

Also, if you want the faucet button to be the primary action on the wallet page, then it should be in an action color like green to signal I need to press it.

**Comment by LuizAsFight** [comment]
what if I added liquidity used all my ETH and got to zero balance, should it faucet me more?
